### ISSUE TITLE
networking:initcms:install : TypeError: Cannot read property 'contents' of undefined

### ISSUE THREAD

**Issue by eli-g** [networking/init-cms-bundle#27]
I get the following error when I am trying to install this on a windows machine:

C:\Users\admin\AppData\Roaming\npm\node_modules\less\lib\less\parser\parser.js:108
            imports.contents[fileInfo.filename] = str;
                   ^
TypeError: Cannot read property 'contents' of undefined
    at Object.Parser.parse (C:\Users\admin\AppData\Roaming\npm\node_modules\less\lib\less\parser\parser.js:108:20)
    at Object.<anonymous> (C:\Users\elinor.gilbert\AppData\Local\Temp\ass4662.tmp:4:187)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

Am I doing something wrong?

**Comment by ychadwick** [comment]
I do not have the necessary experience on a Windows machine sorry. Of I would you I would look into your node is setup
